add_newline = false

[character]
format = "ğŸš€â¯â¯ "
success_symbol = "ğŸš€â¯â¯(bold green) "
error_symbol = "ğŸš€â¯â¯(bold red) "

[directory]
truncation_length = 100
truncate_to_repo = false

[git_branch]
symbol = "ğŸŒ± "